-- ============================================================================
-- 0009_full_catalogue.sql — the full Fay & Partenaires product catalogue.
--
-- 0007 seeded a dozen demo items so the app had something to show on first
-- boot. This migration fills the catalogue out to the real range Fay stocks:
-- boulonnerie, visserie, écrous, rondelles, tiges d'ancrage and roulements,
-- across the common diameters, lengths, grades and finishes.
--
-- Rules honoured here (unchanged from 0002 / 0007):
--   * Prices below are BACK-OFFICE ONLY. The storefront RPCs never return them;
--     the admin refines them from the dashboard. They exist so the accounting
--     and margin tools have something to work with.
--   * Every product carries a real photo in `image_url`, pointing at a brochure
--     photograph shipped in /public. mediaUrl() passes a leading-"/" value
--     straight through, so these render without Supabase Storage.
--   * Idempotent: ON CONFLICT (slug) DO NOTHING. Re-running the bundle — or
--     re-applying after the admin has edited a product — changes nothing.
-- ============================================================================

insert into products (slug, sku, name, category_id, description, material, specs, unit, pack_size, image_url, cost_price, sale_price, quantity, low_stock_at, is_featured)
select v.slug, v.sku, v.name,
       (select id from categories c where c.slug = v.cat),
       v.description, v.material, v.specs::jsonb, v.unit, v.pack_size, v.image_url,
       v.cost_price, v.sale_price, v.quantity, v.low_stock_at, v.is_featured
from (values
    -- ── Boulonnerie ────────────────────────────────────────────────────────
    ('boulon-hm-8x30', 'BLN-0830', 'Boulon HM 8 x 30', 'boulonnerie',
     'Boulon tête hexagonale, filetage métrique, classe 8.8.', 'Acier au carbone zingué',
     '{"Diamètre":"M8","Longueur":"30 mm","Classe":"8.8","Filetage":"Métrique"}',
     'boîte', 'Boîte de 200', '/catalog/gallery/boulonnerie/g01.jpg', 9000, 14000, 320, 60, false),
    ('boulon-hm-8x50', 'BLN-0850', 'Boulon HM 8 x 50', 'boulonnerie',
     'Boulon tête hexagonale, filetage métrique, classe 8.8.', 'Acier au carbone zingué',
     '{"Diamètre":"M8","Longueur":"50 mm","Classe":"8.8","Filetage":"Métrique"}',
     'boîte', 'Boîte de 100', '/catalog/gallery/boulonnerie/g02.jpg', 11000, 16000, 210, 40, false),
    ('boulon-hm-10x60', 'BLN-1060', 'Boulon HM 10 x 60', 'boulonnerie',
     'Boulon tête hexagonale haute résistance, classe 8.8.', 'Acier au carbone zingué',
     '{"Diamètre":"M10","Longueur":"60 mm","Classe":"8.8","Filetage":"Métrique"}',
     'boîte', 'Boîte de 100', '/catalog/gallery/boulonnerie/g03.jpg', 16000, 24000, 180, 35, true),
    ('boulon-hm-10x80', 'BLN-1080', 'Boulon HM 10 x 80', 'boulonnerie',
     'Boulon tête hexagonale, filetage partiel, classe 8.8.', 'Acier au carbone zingué',
     '{"Diamètre":"M10","Longueur":"80 mm","Classe":"8.8","Filetage":"Partiel"}',
     'boîte', 'Boîte de 50', '/catalog/gallery/boulonnerie/g04.jpg', 18000, 27000, 130, 30, false),
    ('boulon-hm-12x40', 'BLN-1240', 'Boulon HM 12 x 40', 'boulonnerie',
     'Boulon tête hexagonale, filetage total, classe 8.8.', 'Acier au carbone zingué',
     '{"Diamètre":"M12","Longueur":"40 mm","Classe":"8.8","Filetage":"Total"}',
     'boîte', 'Boîte de 100', '/catalog/gallery/boulonnerie/g05.jpg', 17000, 25000, 160, 30, false),
    ('boulon-hm-12x80', 'BLN-1280', 'Boulon HM 12 x 80', 'boulonnerie',
     'Boulon tête hexagonale haute résistance pour charpente.', 'Acier allié galvanisé à chaud',
     '{"Diamètre":"M12","Longueur":"80 mm","Classe":"10.9","Finition":"Galvanisé à chaud"}',
     'boîte', 'Boîte de 50', '/catalog/gallery/boulonnerie/g06.jpg', 24000, 35000, 90, 20, true),
    ('boulon-hm-14x70', 'BLN-1470', 'Boulon HM 14 x 70', 'boulonnerie',
     'Boulon tête hexagonale, classe 8.8, pour assemblages lourds.', 'Acier au carbone zingué',
     '{"Diamètre":"M14","Longueur":"70 mm","Classe":"8.8","Filetage":"Partiel"}',
     'boîte', 'Boîte de 50', '/catalog/gallery/boulonnerie/g07.jpg', 26000, 38000, 70, 15, false),
    ('boulon-hm-16x60', 'BLN-1660', 'Boulon HM 16 x 60', 'boulonnerie',
     'Boulon tête hexagonale, classe 8.8, filetage total.', 'Acier au carbone zingué',
     '{"Diamètre":"M16","Longueur":"60 mm","Classe":"8.8","Filetage":"Total"}',
     'boîte', 'Boîte de 25', '/catalog/gallery/boulonnerie/g08.jpg', 28000, 41000, 60, 12, false),
    ('boulon-hm-16x100', 'BLN-16100', 'Boulon HM 16 x 100', 'boulonnerie',
     'Boulon tête hexagonale haute résistance pour charpente métallique.', 'Acier allié galvanisé à chaud',
     '{"Diamètre":"M16","Longueur":"100 mm","Classe":"10.9","Finition":"Galvanisé à chaud"}',
     'boîte', 'Boîte de 25', '/catalog/gallery/boulonnerie/g09.jpg', 34000, 49000, 45, 10, true),
    ('boulon-hm-20x80', 'BLN-2080', 'Boulon HM 20 x 80', 'boulonnerie',
     'Boulon tête hexagonale de forte section pour ouvrages métalliques.', 'Acier allié galvanisé à chaud',
     '{"Diamètre":"M20","Longueur":"80 mm","Classe":"10.9","Finition":"Galvanisé à chaud"}',
     'boîte', 'Boîte de 20', '/catalog/gallery/boulonnerie/g10.jpg', 42000, 60000, 30, 8, false),
    ('boulon-chc-8x40', 'BLN-C840', 'Vis CHC 8 x 40 (BTR)', 'boulonnerie',
     'Vis à tête cylindrique à six pans creux (BTR), classe 12.9.', 'Acier allié brut noir',
     '{"Diamètre":"M8","Longueur":"40 mm","Empreinte":"Six pans creux","Classe":"12.9"}',
     'boîte', 'Boîte de 100', '/catalog/gallery/boulonnerie/g11.jpg', 15000, 23000, 140, 30, false),
    ('boulon-inox-10x50', 'BLN-I1050', 'Boulon HM inox 10 x 50', 'boulonnerie',
     'Boulon tête hexagonale en inox A2, résistant à la corrosion.', 'Acier inoxydable A2 (304)',
     '{"Diamètre":"M10","Longueur":"50 mm","Matière":"Inox A2","Filetage":"Métrique"}',
     'boîte', 'Boîte de 50', '/catalog/gallery/boulonnerie/g12.jpg', 26000, 39000, 85, 20, true),

    -- ── Visserie ───────────────────────────────────────────────────────────
    ('vis-tole-4-2x13', 'VIS-4213', 'Vis à tôle 4.2 x 13', 'visserie',
     'Vis autoperceuse tête bombée cruciforme pour tôle fine.', 'Acier zingué',
     '{"Diamètre":"4.2 mm","Longueur":"13 mm","Empreinte":"Phillips","Tête":"Bombée"}',
     'sachet', 'Sachet de 500', '/catalog/gallery/visserie/g01.jpg', 4500, 7000, 260, 50, false),
    ('vis-tole-6-3x25', 'VIS-6325', 'Vis à tôle 6.3 x 25', 'visserie',
     'Vis autoperceuse tête hexagonale pour bac acier et couverture.', 'Acier zingué bichromaté',
     '{"Diamètre":"6.3 mm","Longueur":"25 mm","Empreinte":"Hexagonale","Tête":"Hexagonale à embase"}',
     'boîte', 'Boîte de 250', '/catalog/gallery/visserie/g02.jpg', 8000, 12500, 180, 40, true),
    ('vis-bois-4x40', 'VIS-0440', 'Vis à bois 4 x 40', 'visserie',
     'Vis à bois filetage partiel, tête fraisée Pozidriv.', 'Acier zingué',
     '{"Diamètre":"4 mm","Longueur":"40 mm","Empreinte":"Pozidriv","Tête":"Fraisée"}',
     'boîte', 'Boîte de 500', '/catalog/gallery/visserie/g03.jpg', 6000, 9500, 220, 45, false),
    ('vis-bois-6x80', 'VIS-0680', 'Vis à bois 6 x 80', 'visserie',
     'Vis à bois haute performance, tête fraisée Torx, filetage partiel.', 'Acier zingué',
     '{"Diamètre":"6 mm","Longueur":"80 mm","Empreinte":"Torx","Tête":"Fraisée"}',
     'boîte', 'Boîte de 100', '/catalog/gallery/visserie/g04.jpg', 9000, 14000, 120, 25, false),
    ('vis-agglo-4x30', 'VIS-A430', 'Vis à aggloméré 4 x 30', 'visserie',
     'Vis universelle à aggloméré, tête fraisée Pozidriv, filetage total.', 'Acier zingué jaune',
     '{"Diamètre":"4 mm","Longueur":"30 mm","Empreinte":"Pozidriv","Filetage":"Total"}',
     'boîte', 'Boîte de 1000', '/catalog/gallery/visserie/g05.jpg', 7000, 11000, 300, 60, true),
    ('vis-placo-3-5x25', 'VIS-P3525', 'Vis à placo 3.5 x 25', 'visserie',
     'Vis pour plaque de plâtre, tête trompette, filetage fin.', 'Acier phosphaté noir',
     '{"Diamètre":"3.5 mm","Longueur":"25 mm","Empreinte":"Phillips","Tête":"Trompette"}',
     'boîte', 'Boîte de 1000', '/catalog/gallery/visserie/g06.jpg', 5000, 8000, 340, 70, false),
    ('vis-chc-m6x20', 'VIS-C620', 'Vis CHC M6 x 20 (BTR)', 'visserie',
     'Vis à tête cylindrique à six pans creux (BTR), classe 12.9.', 'Acier allié brut noir',
     '{"Diamètre":"M6","Longueur":"20 mm","Empreinte":"Six pans creux","Classe":"12.9"}',
     'sachet', 'Sachet de 200', '/catalog/gallery/visserie/g01.jpg', 6500, 10000, 200, 40, false),
    ('vis-autoperceuse-5-5x25', 'VIS-AP5525', 'Vis autoperceuse 5.5 x 25', 'visserie',
     'Vis autoperceuse tête hexagonale à embase crantée, pointe foret.', 'Acier zingué',
     '{"Diamètre":"5.5 mm","Longueur":"25 mm","Empreinte":"Hexagonale","Pointe":"Foret"}',
     'boîte', 'Boîte de 250', '/catalog/gallery/visserie/g02.jpg', 7500, 11500, 160, 35, false),

    -- ── Écrous ─────────────────────────────────────────────────────────────
    ('ecrou-hexagonal-m6', 'ECR-M06', 'Écrou hexagonal M6', 'ecrous',
     'Écrou hexagonal standard ISO 4032.', 'Acier au carbone zingué',
     '{"Diamètre":"M6","Type":"Hexagonal","Norme":"ISO 4032"}',
     'sachet', 'Sachet de 500', '/catalog/gallery/ecrous/g01.jpg', 3000, 5000, 500, 100, false),
    ('ecrou-hexagonal-m8', 'ECR-M08', 'Écrou hexagonal M8', 'ecrous',
     'Écrou hexagonal standard ISO 4032.', 'Acier au carbone zingué',
     '{"Diamètre":"M8","Type":"Hexagonal","Norme":"ISO 4032"}',
     'boîte', 'Boîte de 500', '/catalog/gallery/ecrous/g02.jpg', 3500, 5800, 420, 80, false),
    ('ecrou-hexagonal-m12', 'ECR-M12B', 'Écrou hexagonal M12', 'ecrous',
     'Écrou hexagonal standard ISO 4032.', 'Acier au carbone zingué',
     '{"Diamètre":"M12","Type":"Hexagonal","Norme":"ISO 4032"}',
     'boîte', 'Boîte de 200', '/catalog/gallery/ecrous/g03.jpg', 5000, 8000, 280, 55, true),
    ('ecrou-hexagonal-m16', 'ECR-M16', 'Écrou hexagonal M16', 'ecrous',
     'Écrou hexagonal standard ISO 4032, forte section.', 'Acier au carbone zingué',
     '{"Diamètre":"M16","Type":"Hexagonal","Norme":"ISO 4032"}',
     'boîte', 'Boîte de 100', '/catalog/gallery/ecrous/g04.jpg', 7000, 11000, 150, 30, false),
    ('ecrou-frein-m8', 'ECR-F08', 'Écrou frein M8', 'ecrous',
     'Écrou autofreiné à bague nylon (Nylstop).', 'Acier + bague nylon',
     '{"Diamètre":"M8","Type":"Frein (Nylstop)","Matière bague":"Nylon"}',
     'boîte', 'Boîte de 200', '/catalog/gallery/ecrous/g05.jpg', 4500, 7000, 240, 50, false),
    ('ecrou-frein-m10', 'ECR-F10', 'Écrou frein M10', 'ecrous',
     'Écrou autofreiné à bague nylon (Nylstop).', 'Acier + bague nylon',
     '{"Diamètre":"M10","Type":"Frein (Nylstop)","Matière bague":"Nylon"}',
     'boîte', 'Boîte de 200', '/catalog/gallery/ecrous/g06.jpg', 5000, 8000, 200, 40, true),
    ('ecrou-borgne-m10', 'ECR-B10', 'Écrou borgne M10', 'ecrous',
     'Écrou borgne (chapeau) de finition, DIN 1587.', 'Acier laitonné',
     '{"Diamètre":"M10","Type":"Borgne (chapeau)","Norme":"DIN 1587"}',
     'sachet', 'Sachet de 100', '/catalog/gallery/ecrous/g07.jpg', 5500, 8500, 120, 25, false),
    ('ecrou-a-embase-m8', 'ECR-E08', 'Écrou à embase crantée M8', 'ecrous',
     'Écrou hexagonal à embase crantée anti-desserrage, DIN 6923.', 'Acier au carbone zingué',
     '{"Diamètre":"M8","Type":"À embase crantée","Norme":"DIN 6923"}',
     'boîte', 'Boîte de 200', '/catalog/gallery/ecrous/g08.jpg', 4500, 7200, 180, 40, false),
    ('ecrou-a-souder-m10', 'ECR-S10', 'Écrou à souder M10', 'ecrous',
     'Écrou hexagonal à souder, avec picots de centrage, DIN 929.', 'Acier brut',
     '{"Diamètre":"M10","Type":"À souder","Norme":"DIN 929"}',
     'sachet', 'Sachet de 100', '/catalog/gallery/ecrous/g09.jpg', 5000, 8000, 130, 30, false),
    ('ecrou-carre-m8', 'ECR-C08', 'Écrou carré M8', 'ecrous',
     'Écrou carré pour rail et profilé, DIN 557.', 'Acier au carbone zingué',
     '{"Diamètre":"M8","Type":"Carré","Norme":"DIN 557"}',
     'sachet', 'Sachet de 200', '/catalog/gallery/ecrous/g10.jpg', 4000, 6500, 160, 35, false),

    -- ── Rondelles ──────────────────────────────────────────────────────────
    ('rondelle-plate-m8', 'RND-P08', 'Rondelle plate M8', 'rondelles',
     'Rondelle plate moyenne ISO 7089.', 'Acier au carbone zingué',
     '{"Diamètre intérieur":"8,4 mm","Type":"Plate","Norme":"ISO 7089"}',
     'sachet', 'Sachet de 500', '/catalog/gallery/rondelles/g01.jpg', 2500, 4200, 500, 100, false),
    ('rondelle-plate-m12', 'RND-P12', 'Rondelle plate M12', 'rondelles',
     'Rondelle plate large ISO 7093.', 'Acier au carbone zingué',
     '{"Diamètre intérieur":"13 mm","Type":"Plate large","Norme":"ISO 7093"}',
     'sachet', 'Sachet de 500', '/catalog/gallery/rondelles/g02.jpg', 3200, 5200, 380, 75, true),
    ('rondelle-plate-m16', 'RND-P16', 'Rondelle plate M16', 'rondelles',
     'Rondelle plate large ISO 7093, forte section.', 'Acier au carbone zingué',
     '{"Diamètre intérieur":"17 mm","Type":"Plate large","Norme":"ISO 7093"}',
     'sachet', 'Sachet de 250', '/catalog/gallery/rondelles/g03.jpg', 4000, 6500, 260, 55, false),
    ('rondelle-eventail-m10', 'RND-E10', 'Rondelle éventail M10', 'rondelles',
     'Rondelle éventail (dentée extérieure) anti-desserrage.', 'Acier ressort zingué',
     '{"Diamètre":"M10","Type":"Éventail (dentée)","Norme":"DIN 6798"}',
     'sachet', 'Sachet de 500', '/catalog/gallery/rondelles/g04.jpg', 3000, 5000, 300, 60, false),
    ('rondelle-grower-m12', 'RND-G12', 'Rondelle Grower M12', 'rondelles',
     'Rondelle élastique fendue (grower) anti-desserrage.', 'Acier ressort',
     '{"Diamètre":"M12","Type":"Grower (fendue)","Norme":"DIN 127"}',
     'sachet', 'Sachet de 500', '/catalog/gallery/rondelles/g05.jpg', 3800, 6000, 240, 50, false),
    ('rondelle-cuvette-m6', 'RND-C06', 'Rondelle cuvette M6', 'rondelles',
     'Rondelle cuvette de finition pour vis à tête fraisée.', 'Acier laitonné',
     '{"Diamètre":"M6","Type":"Cuvette","Usage":"Finition tête fraisée"}',
     'sachet', 'Sachet de 500', '/catalog/gallery/rondelles/g01.jpg', 2800, 4600, 280, 55, false),

    -- ── Tiges d'ancrage ──────────────────────────────────────────────────────
    ('tige-filetee-m8-1m', 'TIG-M08', 'Tige filetée M8 — 1 m', 'tiges-d-ancrage',
     'Tige filetée métrique en barre de 1 mètre, filetage intégral.', 'Acier zingué',
     '{"Diamètre":"M8","Longueur":"1000 mm","Filetage":"Métrique intégral"}',
     'lot', 'Lot de 10 barres', '/catalog/cat-tiges-d-ancrage.jpg', 12000, 19000, 60, 12, false),
    ('tige-filetee-m10-1m', 'TIG-M10', 'Tige filetée M10 — 1 m', 'tiges-d-ancrage',
     'Tige filetée métrique en barre de 1 mètre, filetage intégral.', 'Acier zingué',
     '{"Diamètre":"M10","Longueur":"1000 mm","Filetage":"Métrique intégral"}',
     'lot', 'Lot de 10 barres', '/catalog/prod-tige-filetee-m12-1m.jpg', 15000, 23000, 55, 12, true),
    ('tige-filetee-m16-1m', 'TIG-M16', 'Tige filetée M16 — 1 m', 'tiges-d-ancrage',
     'Tige filetée métrique en barre de 1 mètre, forte section.', 'Acier zingué',
     '{"Diamètre":"M16","Longueur":"1000 mm","Filetage":"Métrique intégral"}',
     'lot', 'Lot de 10 barres', '/catalog/gallery/rondelles/g02.jpg', 24000, 36000, 35, 8, false),
    ('tige-ancrage-m12', 'TIG-A12', 'Tige d''ancrage M12', 'tiges-d-ancrage',
     'Tige d''ancrage à scellement chimique ou mécanique pour béton.', 'Acier galvanisé à chaud',
     '{"Diamètre":"M12","Type":"Ancrage / scellement","Finition":"Galvanisé à chaud"}',
     'lot', 'Lot de 25', '/catalog/prod-tige-ancrage-m16.jpg', 24000, 36000, 40, 10, false),
    ('tige-ancrage-m20', 'TIG-A20', 'Tige d''ancrage M20', 'tiges-d-ancrage',
     'Tige d''ancrage forte section pour charpente et génie civil.', 'Acier galvanisé à chaud',
     '{"Diamètre":"M20","Type":"Ancrage / scellement","Finition":"Galvanisé à chaud"}',
     'lot', 'Lot de 20', '/catalog/cat-tiges-d-ancrage.jpg', 40000, 58000, 25, 6, true),
    ('goujon-ancrage-m10x100', 'GJN-10100', 'Goujon d''ancrage M10 x 100', 'tiges-d-ancrage',
     'Goujon d''ancrage à expansion pour fixation lourde dans le béton.', 'Acier zingué',
     '{"Diamètre":"M10","Longueur":"100 mm","Type":"Goujon à expansion"}',
     'boîte', 'Boîte de 50', '/catalog/gallery/rondelles/g03.jpg', 18000, 28000, 70, 15, false),

    -- ── Roulements ─────────────────────────────────────────────────────────
    ('roulement-6200-2rs', 'RLT-6200', 'Roulement 6200 2RS', 'roulements',
     'Roulement à billes étanche, gorge profonde.', 'Acier chromé',
     '{"Référence":"6200-2RS","Alésage":"10 mm","Extérieur":"30 mm","Largeur":"9 mm"}',
     'pièce', 'À l''unité', '/catalog/gallery/roulements/g01.jpg', 2500, 4500, 90, 18, false),
    ('roulement-6201-2rs', 'RLT-6201', 'Roulement 6201 2RS', 'roulements',
     'Roulement à billes étanche, gorge profonde.', 'Acier chromé',
     '{"Référence":"6201-2RS","Alésage":"12 mm","Extérieur":"32 mm","Largeur":"10 mm"}',
     'pièce', 'À l''unité', '/catalog/gallery/roulements/g02.jpg', 2800, 5000, 85, 18, false),
    ('roulement-6202-2rs', 'RLT-6202', 'Roulement 6202 2RS', 'roulements',
     'Roulement à billes étanche, gorge profonde.', 'Acier chromé',
     '{"Référence":"6202-2RS","Alésage":"15 mm","Extérieur":"35 mm","Largeur":"11 mm"}',
     'pièce', 'À l''unité', '/catalog/gallery/roulements/g03.jpg', 3000, 5500, 80, 16, true),
    ('roulement-6203-2rs', 'RLT-6203', 'Roulement 6203 2RS', 'roulements',
     'Roulement à billes étanche, gorge profonde.', 'Acier chromé',
     '{"Référence":"6203-2RS","Alésage":"17 mm","Extérieur":"40 mm","Largeur":"12 mm"}',
     'pièce', 'À l''unité', '/catalog/gallery/roulements/g04.jpg', 3200, 5800, 78, 16, false),
    ('roulement-6206-2rs', 'RLT-6206', 'Roulement 6206 2RS', 'roulements',
     'Roulement à billes étanche, gorge profonde.', 'Acier chromé',
     '{"Référence":"6206-2RS","Alésage":"30 mm","Extérieur":"62 mm","Largeur":"16 mm"}',
     'pièce', 'À l''unité', '/catalog/gallery/roulements/g01.jpg', 4500, 8000, 50, 12, true),
    ('roulement-6301-2rs', 'RLT-6301', 'Roulement 6301 2RS', 'roulements',
     'Roulement à billes étanche, série moyenne, gorge profonde.', 'Acier chromé',
     '{"Référence":"6301-2RS","Alésage":"12 mm","Extérieur":"37 mm","Largeur":"12 mm"}',
     'pièce', 'À l''unité', '/catalog/gallery/roulements/g02.jpg', 3300, 6000, 60, 14, false),
    ('roulement-6302-2rs', 'RLT-6302', 'Roulement 6302 2RS', 'roulements',
     'Roulement à billes étanche, série moyenne, gorge profonde.', 'Acier chromé',
     '{"Référence":"6302-2RS","Alésage":"15 mm","Extérieur":"42 mm","Largeur":"13 mm"}',
     'pièce', 'À l''unité', '/catalog/gallery/roulements/g03.jpg', 3600, 6500, 55, 12, false),
    ('roulement-6203-zz', 'RLT-6203ZZ', 'Roulement 6203 ZZ', 'roulements',
     'Roulement à billes à flasques métalliques, gorge profonde.', 'Acier chromé',
     '{"Référence":"6203-ZZ","Alésage":"17 mm","Extérieur":"40 mm","Largeur":"12 mm","Étanchéité":"Flasques ZZ"}',
     'pièce', 'À l''unité', '/catalog/gallery/roulements/g04.jpg', 3000, 5500, 65, 14, false)
) as v(slug, sku, name, cat, description, material, specs, unit, pack_size, image_url, cost_price, sale_price, quantity, low_stock_at, is_featured)
on conflict (slug) do nothing;

-- Record the opening stock as opening movements for any product that has none
-- yet (same idempotent guard as 0007, so demo + full catalogue coexist safely).
insert into stock_movements (product_id, kind, quantity, unit_cost, note)
select p.id, 'opening', p.quantity, p.cost_price, 'Stock initial (catalogue)'
from products p
where p.quantity > 0
  and not exists (select 1 from stock_movements m where m.product_id = p.id);
